name: ollama
services:
  autollama:
    container_name: ollama
    image: ollama/ollama
    networks:
      default: null
    ports:
      - mode: ingress
        target: 11434
        published: "11434"
        protocol: tcp
    volumes:
      - type: bind
        source: .
        target: /root/.ollama
        bind:
          create_host_path: true
networks:
  default:
    name: ollama_default 